// Add New Data
export const PROCESSFORMDATA_START = "PROCESSFORMDATA_START";
export const PROCESSFORMDATA_SUCCESS = "PROCESSFORMDATA_SUCCESS";
export const PROCESSFORMDATA_FAILED = "PROCESSFORMDATA_FAILED";

// Fetch Data of Results
export const FETCH_RESULT = "FETCH_RESULT";
export const FETCH_RESULT_FAILED = "FETCH_RESULT_FAILED";

// Delete Results
export const DELETE_RESULT_START = "DELETE_RESULT_START";
export const DELETE_RESULT_SUCCESS = "DELETE_RESULT_SUCCESS";
export const DELETE_RESULT_FAILED = "DELETE_RESULT_FAILED";

// Edit Result 
export const EDIT_RESULT_FIND_SUCCESS = "EDIT_RESULT_FIND_SUCCESS";
export const EDIT_RESULT_FIND_FAILED = "EDIT_RESULT_FIND_FAILED";

export const EDIT_RESULT_START = "EDIT_RESULT_START";
export const EDIT_RESULT_SUCCESS = "EDIT_RESULT_SUCCESS";
export const EDIT_RESULT_FAILED = "EDIT_RESULT_FAILED";

// Home Data
export const HOME_DATA = "HOME_DATA";
